name: Build, test and lint

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        build_type: [Debug, ReleaseSafe, ReleaseFast]
      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - run: sudo apt-get install -y libwayland-dev libegl-dev
      - run: zig build -Doptimize=${{matrix.build_type}} --summary all

  test:
    strategy:
      matrix:
        build_type: [Debug, ReleaseSafe, ReleaseFast]
      fail-fast: false
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - run: sudo apt-get install -y libwayland-dev libegl-dev
      - run: zig build -Doptimize=${{matrix.build_type}} test --summary all

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.14.0
      - run: sudo apt-get install -y libwayland-dev libegl-dev
      - run: zig fmt --check .
